(cl:defpackage rbe500-srv
  (:use )
  (:export
   "JOINTCONTROL"
   "<JOINTCONTROL-REQUEST>"
   "JOINTCONTROL-REQUEST"
   "<JOINTCONTROL-RESPONSE>"
   "JOINTCONTROL-RESPONSE"
   "GET_JOINT_VELOCITIES"
   "<GET_JOINT_VELOCITIES-REQUEST>"
   "GET_JOINT_VELOCITIES-REQUEST"
   "<GET_JOINT_VELOCITIES-RESPONSE>"
   "GET_JOINT_VELOCITIES-RESPONSE"
   "GET_TOOL_VELOCITY"
   "<GET_TOOL_VELOCITY-REQUEST>"
   "GET_TOOL_VELOCITY-REQUEST"
   "<GET_TOOL_VELOCITY-RESPONSE>"
   "GET_TOOL_VELOCITY-RESPONSE"
   "POSE_INPUT"
   "<POSE_INPUT-REQUEST>"
   "POSE_INPUT-REQUEST"
   "<POSE_INPUT-RESPONSE>"
   "POSE_INPUT-RESPONSE"
  ))

