// Generated by gencpp from file rbe500/get_joint_velocitiesResponse.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_GET_JOINT_VELOCITIESRESPONSE_H
#define RBE500_MESSAGE_GET_JOINT_VELOCITIESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe500
{
template <class ContainerAllocator>
struct get_joint_velocitiesResponse_
{
  typedef get_joint_velocitiesResponse_<ContainerAllocator> Type;

  get_joint_velocitiesResponse_()
    : theta_1_dot(0.0)
    , theta_2_dot(0.0)
    , d3_dot(0.0)  {
    }
  get_joint_velocitiesResponse_(const ContainerAllocator& _alloc)
    : theta_1_dot(0.0)
    , theta_2_dot(0.0)
    , d3_dot(0.0)  {
  (void)_alloc;
    }



   typedef double _theta_1_dot_type;
  _theta_1_dot_type theta_1_dot;

   typedef double _theta_2_dot_type;
  _theta_2_dot_type theta_2_dot;

   typedef double _d3_dot_type;
  _d3_dot_type d3_dot;





  typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_joint_velocitiesResponse_

typedef ::rbe500::get_joint_velocitiesResponse_<std::allocator<void> > get_joint_velocitiesResponse;

typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesResponse > get_joint_velocitiesResponsePtr;
typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesResponse const> get_joint_velocitiesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator1> & lhs, const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.theta_1_dot == rhs.theta_1_dot &&
    lhs.theta_2_dot == rhs.theta_2_dot &&
    lhs.d3_dot == rhs.d3_dot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator1> & lhs, const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbe500

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90f5ea939ed53b23bf097187454966f0";
  }

  static const char* value(const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90f5ea939ed53b23ULL;
  static const uint64_t static_value2 = 0xbf097187454966f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe500/get_joint_velocitiesResponse";
  }

  static const char* value(const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 theta_1_dot\n"
"float64 theta_2_dot\n"
"float64 d3_dot\n"
"\n"
;
  }

  static const char* value(const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_1_dot);
      stream.next(m.theta_2_dot);
      stream.next(m.d3_dot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_joint_velocitiesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe500::get_joint_velocitiesResponse_<ContainerAllocator>& v)
  {
    s << indent << "theta_1_dot: ";
    Printer<double>::stream(s, indent + "  ", v.theta_1_dot);
    s << indent << "theta_2_dot: ";
    Printer<double>::stream(s, indent + "  ", v.theta_2_dot);
    s << indent << "d3_dot: ";
    Printer<double>::stream(s, indent + "  ", v.d3_dot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE500_MESSAGE_GET_JOINT_VELOCITIESRESPONSE_H
