// Generated by gencpp from file rbe500/get_tool_velocity.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_GET_TOOL_VELOCITY_H
#define RBE500_MESSAGE_GET_TOOL_VELOCITY_H

#include <ros/service_traits.h>


#include <rbe500/get_tool_velocityRequest.h>
#include <rbe500/get_tool_velocityResponse.h>


namespace rbe500
{

struct get_tool_velocity
{

typedef get_tool_velocityRequest Request;
typedef get_tool_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_tool_velocity
} // namespace rbe500


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbe500::get_tool_velocity > {
  static const char* value()
  {
    return "879ebdb7d19b92561b5fd9d91d6af529";
  }

  static const char* value(const ::rbe500::get_tool_velocity&) { return value(); }
};

template<>
struct DataType< ::rbe500::get_tool_velocity > {
  static const char* value()
  {
    return "rbe500/get_tool_velocity";
  }

  static const char* value(const ::rbe500::get_tool_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::rbe500::get_tool_velocityRequest> should match
// service_traits::MD5Sum< ::rbe500::get_tool_velocity >
template<>
struct MD5Sum< ::rbe500::get_tool_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::get_tool_velocity >::value();
  }
  static const char* value(const ::rbe500::get_tool_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::get_tool_velocityRequest> should match
// service_traits::DataType< ::rbe500::get_tool_velocity >
template<>
struct DataType< ::rbe500::get_tool_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::rbe500::get_tool_velocity >::value();
  }
  static const char* value(const ::rbe500::get_tool_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbe500::get_tool_velocityResponse> should match
// service_traits::MD5Sum< ::rbe500::get_tool_velocity >
template<>
struct MD5Sum< ::rbe500::get_tool_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::get_tool_velocity >::value();
  }
  static const char* value(const ::rbe500::get_tool_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::get_tool_velocityResponse> should match
// service_traits::DataType< ::rbe500::get_tool_velocity >
template<>
struct DataType< ::rbe500::get_tool_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::rbe500::get_tool_velocity >::value();
  }
  static const char* value(const ::rbe500::get_tool_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBE500_MESSAGE_GET_TOOL_VELOCITY_H
