// Generated by gencpp from file rbe500/get_tool_velocityResponse.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_GET_TOOL_VELOCITYRESPONSE_H
#define RBE500_MESSAGE_GET_TOOL_VELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe500
{
template <class ContainerAllocator>
struct get_tool_velocityResponse_
{
  typedef get_tool_velocityResponse_<ContainerAllocator> Type;

  get_tool_velocityResponse_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , wx(0.0)
    , wy(0.0)
    , wz(0.0)  {
    }
  get_tool_velocityResponse_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , wx(0.0)
    , wy(0.0)
    , wz(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;

   typedef double _wx_type;
  _wx_type wx;

   typedef double _wy_type;
  _wy_type wy;

   typedef double _wz_type;
  _wz_type wz;





  typedef boost::shared_ptr< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_tool_velocityResponse_

typedef ::rbe500::get_tool_velocityResponse_<std::allocator<void> > get_tool_velocityResponse;

typedef boost::shared_ptr< ::rbe500::get_tool_velocityResponse > get_tool_velocityResponsePtr;
typedef boost::shared_ptr< ::rbe500::get_tool_velocityResponse const> get_tool_velocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe500::get_tool_velocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbe500::get_tool_velocityResponse_<ContainerAllocator1> & lhs, const ::rbe500::get_tool_velocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.wx == rhs.wx &&
    lhs.wy == rhs.wy &&
    lhs.wz == rhs.wz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbe500::get_tool_velocityResponse_<ContainerAllocator1> & lhs, const ::rbe500::get_tool_velocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbe500

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8848441b29a1bf8fd222cf62b36aa991";
  }

  static const char* value(const ::rbe500::get_tool_velocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8848441b29a1bf8fULL;
  static const uint64_t static_value2 = 0xd222cf62b36aa991ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe500/get_tool_velocityResponse";
  }

  static const char* value(const ::rbe500::get_tool_velocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 wx\n"
"float64 wy\n"
"float64 wz\n"
"\n"
;
  }

  static const char* value(const ::rbe500::get_tool_velocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.wx);
      stream.next(m.wy);
      stream.next(m.wz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_tool_velocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe500::get_tool_velocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe500::get_tool_velocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    s << indent << "wx: ";
    Printer<double>::stream(s, indent + "  ", v.wx);
    s << indent << "wy: ";
    Printer<double>::stream(s, indent + "  ", v.wy);
    s << indent << "wz: ";
    Printer<double>::stream(s, indent + "  ", v.wz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE500_MESSAGE_GET_TOOL_VELOCITYRESPONSE_H
