// Generated by gencpp from file rbe500/get_joint_velocitiesRequest.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_GET_JOINT_VELOCITIESREQUEST_H
#define RBE500_MESSAGE_GET_JOINT_VELOCITIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe500
{
template <class ContainerAllocator>
struct get_joint_velocitiesRequest_
{
  typedef get_joint_velocitiesRequest_<ContainerAllocator> Type;

  get_joint_velocitiesRequest_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , j1(0.0)
    , d3(0.0)  {
    }
  get_joint_velocitiesRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , j1(0.0)
    , d3(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;

   typedef double _j1_type;
  _j1_type j1;

   typedef double _d3_type;
  _d3_type d3;





  typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_joint_velocitiesRequest_

typedef ::rbe500::get_joint_velocitiesRequest_<std::allocator<void> > get_joint_velocitiesRequest;

typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesRequest > get_joint_velocitiesRequestPtr;
typedef boost::shared_ptr< ::rbe500::get_joint_velocitiesRequest const> get_joint_velocitiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator1> & lhs, const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.j1 == rhs.j1 &&
    lhs.d3 == rhs.d3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator1> & lhs, const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbe500

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eea7dceb9f8a9e5b845bd7c3a20ff329";
  }

  static const char* value(const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeea7dceb9f8a9e5bULL;
  static const uint64_t static_value2 = 0x845bd7c3a20ff329ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe500/get_joint_velocitiesRequest";
  }

  static const char* value(const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 j1\n"
"float64 d3\n"
;
  }

  static const char* value(const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.j1);
      stream.next(m.d3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_joint_velocitiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe500::get_joint_velocitiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    s << indent << "j1: ";
    Printer<double>::stream(s, indent + "  ", v.j1);
    s << indent << "d3: ";
    Printer<double>::stream(s, indent + "  ", v.d3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE500_MESSAGE_GET_JOINT_VELOCITIESREQUEST_H
