// Generated by gencpp from file rbe500/get_joint_velocities.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_GET_JOINT_VELOCITIES_H
#define RBE500_MESSAGE_GET_JOINT_VELOCITIES_H

#include <ros/service_traits.h>


#include <rbe500/get_joint_velocitiesRequest.h>
#include <rbe500/get_joint_velocitiesResponse.h>


namespace rbe500
{

struct get_joint_velocities
{

typedef get_joint_velocitiesRequest Request;
typedef get_joint_velocitiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_joint_velocities
} // namespace rbe500


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbe500::get_joint_velocities > {
  static const char* value()
  {
    return "4095fce8d49a55d344a8363f4d43907a";
  }

  static const char* value(const ::rbe500::get_joint_velocities&) { return value(); }
};

template<>
struct DataType< ::rbe500::get_joint_velocities > {
  static const char* value()
  {
    return "rbe500/get_joint_velocities";
  }

  static const char* value(const ::rbe500::get_joint_velocities&) { return value(); }
};


// service_traits::MD5Sum< ::rbe500::get_joint_velocitiesRequest> should match
// service_traits::MD5Sum< ::rbe500::get_joint_velocities >
template<>
struct MD5Sum< ::rbe500::get_joint_velocitiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::get_joint_velocities >::value();
  }
  static const char* value(const ::rbe500::get_joint_velocitiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::get_joint_velocitiesRequest> should match
// service_traits::DataType< ::rbe500::get_joint_velocities >
template<>
struct DataType< ::rbe500::get_joint_velocitiesRequest>
{
  static const char* value()
  {
    return DataType< ::rbe500::get_joint_velocities >::value();
  }
  static const char* value(const ::rbe500::get_joint_velocitiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbe500::get_joint_velocitiesResponse> should match
// service_traits::MD5Sum< ::rbe500::get_joint_velocities >
template<>
struct MD5Sum< ::rbe500::get_joint_velocitiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::get_joint_velocities >::value();
  }
  static const char* value(const ::rbe500::get_joint_velocitiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::get_joint_velocitiesResponse> should match
// service_traits::DataType< ::rbe500::get_joint_velocities >
template<>
struct DataType< ::rbe500::get_joint_velocitiesResponse>
{
  static const char* value()
  {
    return DataType< ::rbe500::get_joint_velocities >::value();
  }
  static const char* value(const ::rbe500::get_joint_velocitiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBE500_MESSAGE_GET_JOINT_VELOCITIES_H
