// Generated by gencpp from file rbe500/JointControlResponse.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_JOINTCONTROLRESPONSE_H
#define RBE500_MESSAGE_JOINTCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe500
{
template <class ContainerAllocator>
struct JointControlResponse_
{
  typedef JointControlResponse_<ContainerAllocator> Type;

  JointControlResponse_()
    {
    }
  JointControlResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rbe500::JointControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe500::JointControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointControlResponse_

typedef ::rbe500::JointControlResponse_<std::allocator<void> > JointControlResponse;

typedef boost::shared_ptr< ::rbe500::JointControlResponse > JointControlResponsePtr;
typedef boost::shared_ptr< ::rbe500::JointControlResponse const> JointControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe500::JointControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe500::JointControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rbe500

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::JointControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::JointControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::JointControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::JointControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::JointControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::JointControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe500::JointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rbe500::JointControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe500::JointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe500/JointControlResponse";
  }

  static const char* value(const ::rbe500::JointControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe500::JointControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rbe500::JointControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe500::JointControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe500::JointControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rbe500::JointControlResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RBE500_MESSAGE_JOINTCONTROLRESPONSE_H
