// Generated by gencpp from file rbe500/JointControl.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_JOINTCONTROL_H
#define RBE500_MESSAGE_JOINTCONTROL_H

#include <ros/service_traits.h>


#include <rbe500/JointControlRequest.h>
#include <rbe500/JointControlResponse.h>


namespace rbe500
{

struct JointControl
{

typedef JointControlRequest Request;
typedef JointControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointControl
} // namespace rbe500


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbe500::JointControl > {
  static const char* value()
  {
    return "e3d59c5166a351c624cb61d94e16d813";
  }

  static const char* value(const ::rbe500::JointControl&) { return value(); }
};

template<>
struct DataType< ::rbe500::JointControl > {
  static const char* value()
  {
    return "rbe500/JointControl";
  }

  static const char* value(const ::rbe500::JointControl&) { return value(); }
};


// service_traits::MD5Sum< ::rbe500::JointControlRequest> should match
// service_traits::MD5Sum< ::rbe500::JointControl >
template<>
struct MD5Sum< ::rbe500::JointControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::JointControl >::value();
  }
  static const char* value(const ::rbe500::JointControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::JointControlRequest> should match
// service_traits::DataType< ::rbe500::JointControl >
template<>
struct DataType< ::rbe500::JointControlRequest>
{
  static const char* value()
  {
    return DataType< ::rbe500::JointControl >::value();
  }
  static const char* value(const ::rbe500::JointControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbe500::JointControlResponse> should match
// service_traits::MD5Sum< ::rbe500::JointControl >
template<>
struct MD5Sum< ::rbe500::JointControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::JointControl >::value();
  }
  static const char* value(const ::rbe500::JointControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::JointControlResponse> should match
// service_traits::DataType< ::rbe500::JointControl >
template<>
struct DataType< ::rbe500::JointControlResponse>
{
  static const char* value()
  {
    return DataType< ::rbe500::JointControl >::value();
  }
  static const char* value(const ::rbe500::JointControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBE500_MESSAGE_JOINTCONTROL_H
