// Generated by gencpp from file rbe500/pose_input.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_POSE_INPUT_H
#define RBE500_MESSAGE_POSE_INPUT_H

#include <ros/service_traits.h>


#include <rbe500/pose_inputRequest.h>
#include <rbe500/pose_inputResponse.h>


namespace rbe500
{

struct pose_input
{

typedef pose_inputRequest Request;
typedef pose_inputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_input
} // namespace rbe500


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbe500::pose_input > {
  static const char* value()
  {
    return "839a493deb7685894758863e9d9fcb39";
  }

  static const char* value(const ::rbe500::pose_input&) { return value(); }
};

template<>
struct DataType< ::rbe500::pose_input > {
  static const char* value()
  {
    return "rbe500/pose_input";
  }

  static const char* value(const ::rbe500::pose_input&) { return value(); }
};


// service_traits::MD5Sum< ::rbe500::pose_inputRequest> should match
// service_traits::MD5Sum< ::rbe500::pose_input >
template<>
struct MD5Sum< ::rbe500::pose_inputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::pose_input >::value();
  }
  static const char* value(const ::rbe500::pose_inputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::pose_inputRequest> should match
// service_traits::DataType< ::rbe500::pose_input >
template<>
struct DataType< ::rbe500::pose_inputRequest>
{
  static const char* value()
  {
    return DataType< ::rbe500::pose_input >::value();
  }
  static const char* value(const ::rbe500::pose_inputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbe500::pose_inputResponse> should match
// service_traits::MD5Sum< ::rbe500::pose_input >
template<>
struct MD5Sum< ::rbe500::pose_inputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbe500::pose_input >::value();
  }
  static const char* value(const ::rbe500::pose_inputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbe500::pose_inputResponse> should match
// service_traits::DataType< ::rbe500::pose_input >
template<>
struct DataType< ::rbe500::pose_inputResponse>
{
  static const char* value()
  {
    return DataType< ::rbe500::pose_input >::value();
  }
  static const char* value(const ::rbe500::pose_inputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBE500_MESSAGE_POSE_INPUT_H
