// Generated by gencpp from file rbe500/pose_inputRequest.msg
// DO NOT EDIT!


#ifndef RBE500_MESSAGE_POSE_INPUTREQUEST_H
#define RBE500_MESSAGE_POSE_INPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbe500
{
template <class ContainerAllocator>
struct pose_inputRequest_
{
  typedef pose_inputRequest_<ContainerAllocator> Type;

  pose_inputRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  pose_inputRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::rbe500::pose_inputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbe500::pose_inputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pose_inputRequest_

typedef ::rbe500::pose_inputRequest_<std::allocator<void> > pose_inputRequest;

typedef boost::shared_ptr< ::rbe500::pose_inputRequest > pose_inputRequestPtr;
typedef boost::shared_ptr< ::rbe500::pose_inputRequest const> pose_inputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbe500::pose_inputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbe500::pose_inputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbe500::pose_inputRequest_<ContainerAllocator1> & lhs, const ::rbe500::pose_inputRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbe500::pose_inputRequest_<ContainerAllocator1> & lhs, const ::rbe500::pose_inputRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbe500

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::pose_inputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbe500::pose_inputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::pose_inputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbe500::pose_inputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::pose_inputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbe500::pose_inputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbe500::pose_inputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::rbe500::pose_inputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbe500::pose_inputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbe500/pose_inputRequest";
  }

  static const char* value(const ::rbe500::pose_inputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbe500::pose_inputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rbe500::pose_inputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbe500::pose_inputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_inputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbe500::pose_inputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbe500::pose_inputRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBE500_MESSAGE_POSE_INPUTREQUEST_H
