(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BEGINNER_TUTORIALS"
   "<BEGINNER_TUTORIALS-REQUEST>"
   "BEGINNER_TUTORIALS-REQUEST"
   "<BEGINNER_TUTORIALS-RESPONSE>"
   "BEGINNER_TUTORIALS-RESPONSE"
  ))

